/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminActivityEntry {
  'id' : bigint,
  'activityType' : AdminActivityType,
  'content' : string,
  'author' : string,
  'timestamp' : Time,
}
export type AdminActivityType = { 'secondHandListing' : null } |
  { 'forumPost' : null } |
  { 'comment' : null } |
  { 'userRegistration' : null };
export interface AdminModerationItem {
  'id' : bigint,
  'contentId' : bigint,
  'reportCount' : bigint,
  'contentType' : string,
  'author' : string,
  'timestamp' : Time,
  'excerpt' : string,
}
export type AdminReportType = { 'post' : null } |
  { 'comment' : null };
export interface AdminReportedContent {
  'id' : bigint,
  'contentId' : bigint,
  'content' : string,
  'reportCount' : bigint,
  'contentType' : AdminReportType,
  'author' : string,
  'isHidden' : boolean,
  'timestamp' : Time,
}
export interface AdminStats {
  'franceUsers' : bigint,
  'totalForumPosts' : bigint,
  'activeListings' : bigint,
  'reportedContentCount' : bigint,
  'totalUsers' : bigint,
  'switzerlandUsers' : bigint,
  'totalComments' : bigint,
  'newUsersLast7Days' : bigint,
}
export type Category = { 'postpartum' : null } |
  { 'sleep' : null } |
  { 'mentalLoad' : null } |
  { 'organization' : null } |
  { 'pregnancy' : null };
export interface Conversation {
  'id' : bigint,
  'participant1' : Principal,
  'participant2' : Principal,
  'messages' : Array<Message>,
}
export type Country = { 'france' : null } |
  { 'switzerland' : null };
export type ExternalBlob = Uint8Array;
export type FrenchRegion = { 'bourgogneFrancheComte' : null } |
  { 'corse' : null } |
  { 'auvergneRhoneAlpes' : null } |
  { 'centreValDeLoire' : null } |
  { 'paysDeLaLoire' : null } |
  { 'hautsDeFrance' : null } |
  { 'normandie' : null } |
  { 'ileDeFrance' : null } |
  { 'occitanie' : null } |
  { 'nouvelleAquitaine' : null } |
  { 'provenceAlpesCoteAzur' : null } |
  { 'bretagne' : null } |
  { 'grandEst' : null };
export interface Listing {
  'id' : bigint,
  'region' : Region,
  'categories' : Array<string>,
  'title' : string,
  'favorites' : Array<Principal>,
  'description' : string,
  'author' : string,
  'timestamp' : Time,
  'price' : bigint,
  'ageGroup' : string,
  'condition' : ProductCondition,
  'images' : Array<ExternalBlob>,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export type MotherhoodStatus = { 'adultChildren' : null } |
  { 'postpartum' : null } |
  { 'tryingToConceive' : null } |
  { 'youngChildren' : null } |
  { 'teenChildren' : null } |
  { 'pregnant' : null };
export interface Post {
  'id' : bigint,
  'content' : string,
  'isAnonymous' : boolean,
  'author' : string,
  'isHidden' : boolean,
  'timestamp' : Time,
  'category' : Category,
}
export type ProductCondition = { 'new' : null } |
  { 'veryGood' : null } |
  { 'good' : null } |
  { 'used' : null };
export type Region = { 'swissCanton' : SwissCanton } |
  { 'frenchRegion' : FrenchRegion };
export interface Reply {
  'id' : bigint,
  'content' : string,
  'isAnonymous' : boolean,
  'author' : string,
  'isHidden' : boolean,
  'timestamp' : Time,
  'postId' : bigint,
}
export type SwissCanton = { 'fribourg' : null } |
  { 'jura' : null } |
  { 'vaud' : null } |
  { 'valais' : null } |
  { 'geneva' : null } |
  { 'neuchatel' : null };
export type Time = bigint;
export interface UserProfile {
  'bio' : [] | [string],
  'region' : [] | [Region],
  'status' : MotherhoodStatus,
  'country' : [] | [Country],
  'favorites' : Array<bigint>,
  'marketingOptIn' : boolean,
  'listings' : Array<bigint>,
  'name' : string,
  'email' : [] | [string],
  'rulesAccepted' : boolean,
  'posts' : Array<bigint>,
  'profilePicture' : [] | [ExternalBlob],
  'registrationTime' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminGetAllContentForModeration' : ActorMethod<
    [],
    Array<AdminModerationItem>
  >,
  'adminGetRecentActivity' : ActorMethod<[], Array<AdminActivityEntry>>,
  'adminGetReportedContent' : ActorMethod<[], Array<AdminReportedContent>>,
  'adminGetStats' : ActorMethod<[], AdminStats>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [
      string,
      string,
      bigint,
      ProductCondition,
      Region,
      Array<string>,
      string,
      Array<ExternalBlob>,
    ],
    bigint
  >,
  'createPost' : ActorMethod<[Category, string, boolean], bigint>,
  'createReply' : ActorMethod<[bigint, string, boolean], bigint>,
  'getAllConversations' : ActorMethod<[], Array<Conversation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal], [] | [Conversation]>,
  'getCurrentPrincipalId' : ActorMethod<[], string>,
  'getFavoritedListings' : ActorMethod<[], Array<Listing>>,
  'getPublicAllListings' : ActorMethod<[], Array<Listing>>,
  'getPublicAllPosts' : ActorMethod<[], Array<Post>>,
  'getPublicListing' : ActorMethod<[bigint], Listing>,
  'getPublicListingsByCondition' : ActorMethod<
    [ProductCondition],
    Array<Listing>
  >,
  'getPublicListingsByRegion' : ActorMethod<[Region], Array<Listing>>,
  'getPublicPost' : ActorMethod<[bigint], Post>,
  'getPublicPostsByCategory' : ActorMethod<[Category], Array<Post>>,
  'getRepliesByPost' : ActorMethod<[bigint], Array<Reply>>,
  'getUserActivity' : ActorMethod<
    [Principal],
    { 'listings' : Array<Listing>, 'posts' : Array<Post> }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFavorite' : ActorMethod<[bigint], boolean>,
  'reportContent' : ActorMethod<[AdminReportType, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], bigint>,
  'toggleFavorite' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];