/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const AdminModerationItem = IDL.Record({
  'id' : IDL.Nat,
  'contentId' : IDL.Nat,
  'reportCount' : IDL.Nat,
  'contentType' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
  'excerpt' : IDL.Text,
});
export const AdminActivityType = IDL.Variant({
  'secondHandListing' : IDL.Null,
  'forumPost' : IDL.Null,
  'comment' : IDL.Null,
  'userRegistration' : IDL.Null,
});
export const AdminActivityEntry = IDL.Record({
  'id' : IDL.Nat,
  'activityType' : AdminActivityType,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
});
export const AdminReportType = IDL.Variant({
  'post' : IDL.Null,
  'comment' : IDL.Null,
});
export const AdminReportedContent = IDL.Record({
  'id' : IDL.Nat,
  'contentId' : IDL.Nat,
  'content' : IDL.Text,
  'reportCount' : IDL.Nat,
  'contentType' : AdminReportType,
  'author' : IDL.Text,
  'isHidden' : IDL.Bool,
  'timestamp' : Time,
});
export const AdminStats = IDL.Record({
  'franceUsers' : IDL.Nat,
  'totalForumPosts' : IDL.Nat,
  'activeListings' : IDL.Nat,
  'reportedContentCount' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'switzerlandUsers' : IDL.Nat,
  'totalComments' : IDL.Nat,
  'newUsersLast7Days' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductCondition = IDL.Variant({
  'new' : IDL.Null,
  'veryGood' : IDL.Null,
  'good' : IDL.Null,
  'used' : IDL.Null,
});
export const SwissCanton = IDL.Variant({
  'fribourg' : IDL.Null,
  'jura' : IDL.Null,
  'vaud' : IDL.Null,
  'valais' : IDL.Null,
  'geneva' : IDL.Null,
  'neuchatel' : IDL.Null,
});
export const FrenchRegion = IDL.Variant({
  'bourgogneFrancheComte' : IDL.Null,
  'corse' : IDL.Null,
  'auvergneRhoneAlpes' : IDL.Null,
  'centreValDeLoire' : IDL.Null,
  'paysDeLaLoire' : IDL.Null,
  'hautsDeFrance' : IDL.Null,
  'normandie' : IDL.Null,
  'ileDeFrance' : IDL.Null,
  'occitanie' : IDL.Null,
  'nouvelleAquitaine' : IDL.Null,
  'provenceAlpesCoteAzur' : IDL.Null,
  'bretagne' : IDL.Null,
  'grandEst' : IDL.Null,
});
export const Region = IDL.Variant({
  'swissCanton' : SwissCanton,
  'frenchRegion' : FrenchRegion,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'postpartum' : IDL.Null,
  'sleep' : IDL.Null,
  'mentalLoad' : IDL.Null,
  'organization' : IDL.Null,
  'pregnancy' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'participant1' : IDL.Principal,
  'participant2' : IDL.Principal,
  'messages' : IDL.Vec(Message),
});
export const MotherhoodStatus = IDL.Variant({
  'adultChildren' : IDL.Null,
  'postpartum' : IDL.Null,
  'tryingToConceive' : IDL.Null,
  'youngChildren' : IDL.Null,
  'teenChildren' : IDL.Null,
  'pregnant' : IDL.Null,
});
export const Country = IDL.Variant({
  'france' : IDL.Null,
  'switzerland' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'region' : IDL.Opt(Region),
  'status' : MotherhoodStatus,
  'country' : IDL.Opt(Country),
  'favorites' : IDL.Vec(IDL.Nat),
  'marketingOptIn' : IDL.Bool,
  'listings' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'rulesAccepted' : IDL.Bool,
  'posts' : IDL.Vec(IDL.Nat),
  'profilePicture' : IDL.Opt(ExternalBlob),
  'registrationTime' : Time,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'region' : Region,
  'categories' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'favorites' : IDL.Vec(IDL.Principal),
  'description' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
  'price' : IDL.Nat,
  'ageGroup' : IDL.Text,
  'condition' : ProductCondition,
  'images' : IDL.Vec(ExternalBlob),
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'author' : IDL.Text,
  'isHidden' : IDL.Bool,
  'timestamp' : Time,
  'category' : Category,
});
export const Reply = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'author' : IDL.Text,
  'isHidden' : IDL.Bool,
  'timestamp' : Time,
  'postId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetAllContentForModeration' : IDL.Func(
      [],
      [IDL.Vec(AdminModerationItem)],
      ['query'],
    ),
  'adminGetRecentActivity' : IDL.Func(
      [],
      [IDL.Vec(AdminActivityEntry)],
      ['query'],
    ),
  'adminGetReportedContent' : IDL.Func(
      [],
      [IDL.Vec(AdminReportedContent)],
      ['query'],
    ),
  'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ProductCondition,
        Region,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'createPost' : IDL.Func([Category, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'createReply' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'getAllConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Conversation)],
      ['query'],
    ),
  'getCurrentPrincipalId' : IDL.Func([], [IDL.Text], ['query']),
  'getFavoritedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getPublicAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getPublicAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPublicListing' : IDL.Func([IDL.Nat], [Listing], ['query']),
  'getPublicListingsByCondition' : IDL.Func(
      [ProductCondition],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getPublicListingsByRegion' : IDL.Func(
      [Region],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getPublicPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getPublicPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
  'getRepliesByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Reply)], ['query']),
  'getUserActivity' : IDL.Func(
      [IDL.Principal],
      [IDL.Record({ 'listings' : IDL.Vec(Listing), 'posts' : IDL.Vec(Post) })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'reportContent' : IDL.Func([AdminReportType, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const AdminModerationItem = IDL.Record({
    'id' : IDL.Nat,
    'contentId' : IDL.Nat,
    'reportCount' : IDL.Nat,
    'contentType' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
    'excerpt' : IDL.Text,
  });
  const AdminActivityType = IDL.Variant({
    'secondHandListing' : IDL.Null,
    'forumPost' : IDL.Null,
    'comment' : IDL.Null,
    'userRegistration' : IDL.Null,
  });
  const AdminActivityEntry = IDL.Record({
    'id' : IDL.Nat,
    'activityType' : AdminActivityType,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
  });
  const AdminReportType = IDL.Variant({
    'post' : IDL.Null,
    'comment' : IDL.Null,
  });
  const AdminReportedContent = IDL.Record({
    'id' : IDL.Nat,
    'contentId' : IDL.Nat,
    'content' : IDL.Text,
    'reportCount' : IDL.Nat,
    'contentType' : AdminReportType,
    'author' : IDL.Text,
    'isHidden' : IDL.Bool,
    'timestamp' : Time,
  });
  const AdminStats = IDL.Record({
    'franceUsers' : IDL.Nat,
    'totalForumPosts' : IDL.Nat,
    'activeListings' : IDL.Nat,
    'reportedContentCount' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'switzerlandUsers' : IDL.Nat,
    'totalComments' : IDL.Nat,
    'newUsersLast7Days' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductCondition = IDL.Variant({
    'new' : IDL.Null,
    'veryGood' : IDL.Null,
    'good' : IDL.Null,
    'used' : IDL.Null,
  });
  const SwissCanton = IDL.Variant({
    'fribourg' : IDL.Null,
    'jura' : IDL.Null,
    'vaud' : IDL.Null,
    'valais' : IDL.Null,
    'geneva' : IDL.Null,
    'neuchatel' : IDL.Null,
  });
  const FrenchRegion = IDL.Variant({
    'bourgogneFrancheComte' : IDL.Null,
    'corse' : IDL.Null,
    'auvergneRhoneAlpes' : IDL.Null,
    'centreValDeLoire' : IDL.Null,
    'paysDeLaLoire' : IDL.Null,
    'hautsDeFrance' : IDL.Null,
    'normandie' : IDL.Null,
    'ileDeFrance' : IDL.Null,
    'occitanie' : IDL.Null,
    'nouvelleAquitaine' : IDL.Null,
    'provenceAlpesCoteAzur' : IDL.Null,
    'bretagne' : IDL.Null,
    'grandEst' : IDL.Null,
  });
  const Region = IDL.Variant({
    'swissCanton' : SwissCanton,
    'frenchRegion' : FrenchRegion,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'postpartum' : IDL.Null,
    'sleep' : IDL.Null,
    'mentalLoad' : IDL.Null,
    'organization' : IDL.Null,
    'pregnancy' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'participant1' : IDL.Principal,
    'participant2' : IDL.Principal,
    'messages' : IDL.Vec(Message),
  });
  const MotherhoodStatus = IDL.Variant({
    'adultChildren' : IDL.Null,
    'postpartum' : IDL.Null,
    'tryingToConceive' : IDL.Null,
    'youngChildren' : IDL.Null,
    'teenChildren' : IDL.Null,
    'pregnant' : IDL.Null,
  });
  const Country = IDL.Variant({
    'france' : IDL.Null,
    'switzerland' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'region' : IDL.Opt(Region),
    'status' : MotherhoodStatus,
    'country' : IDL.Opt(Country),
    'favorites' : IDL.Vec(IDL.Nat),
    'marketingOptIn' : IDL.Bool,
    'listings' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'rulesAccepted' : IDL.Bool,
    'posts' : IDL.Vec(IDL.Nat),
    'profilePicture' : IDL.Opt(ExternalBlob),
    'registrationTime' : Time,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'region' : Region,
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'favorites' : IDL.Vec(IDL.Principal),
    'description' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
    'price' : IDL.Nat,
    'ageGroup' : IDL.Text,
    'condition' : ProductCondition,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'author' : IDL.Text,
    'isHidden' : IDL.Bool,
    'timestamp' : Time,
    'category' : Category,
  });
  const Reply = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'author' : IDL.Text,
    'isHidden' : IDL.Bool,
    'timestamp' : Time,
    'postId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetAllContentForModeration' : IDL.Func(
        [],
        [IDL.Vec(AdminModerationItem)],
        ['query'],
      ),
    'adminGetRecentActivity' : IDL.Func(
        [],
        [IDL.Vec(AdminActivityEntry)],
        ['query'],
      ),
    'adminGetReportedContent' : IDL.Func(
        [],
        [IDL.Vec(AdminReportedContent)],
        ['query'],
      ),
    'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ProductCondition,
          Region,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func([Category, IDL.Text, IDL.Bool], [IDL.Nat], []),
    'createReply' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [IDL.Nat], []),
    'getAllConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'getCurrentPrincipalId' : IDL.Func([], [IDL.Text], ['query']),
    'getFavoritedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getPublicAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getPublicAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPublicListing' : IDL.Func([IDL.Nat], [Listing], ['query']),
    'getPublicListingsByCondition' : IDL.Func(
        [ProductCondition],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getPublicListingsByRegion' : IDL.Func(
        [Region],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getPublicPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getPublicPostsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getRepliesByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Reply)], ['query']),
    'getUserActivity' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'listings' : IDL.Vec(Listing),
            'posts' : IDL.Vec(Post),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'reportContent' : IDL.Func([AdminReportType, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };