/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductCondition = IDL.Variant({
  'new' : IDL.Null,
  'veryGood' : IDL.Null,
  'good' : IDL.Null,
  'used' : IDL.Null,
});
export const Region = IDL.Variant({
  'fribourg' : IDL.Null,
  'jura' : IDL.Null,
  'vaud' : IDL.Null,
  'valais' : IDL.Null,
  'geneva' : IDL.Null,
  'neuchatel' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'postpartum' : IDL.Null,
  'sleep' : IDL.Null,
  'mentalLoad' : IDL.Null,
  'organization' : IDL.Null,
  'pregnancy' : IDL.Null,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'participant1' : IDL.Principal,
  'participant2' : IDL.Principal,
  'messages' : IDL.Vec(Message),
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'region' : Region,
  'categories' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
  'price' : IDL.Nat,
  'ageGroup' : IDL.Text,
  'condition' : ProductCondition,
  'images' : IDL.Vec(ExternalBlob),
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'author' : IDL.Text,
  'timestamp' : Time,
  'category' : Category,
});
export const Country = IDL.Variant({
  'france' : IDL.Null,
  'switzerland' : IDL.Null,
});
export const MotherhoodStatus = IDL.Variant({
  'adultChildren' : IDL.Null,
  'postpartum' : IDL.Null,
  'tryingToConceive' : IDL.Null,
  'youngChildren' : IDL.Null,
  'teenChildren' : IDL.Null,
  'pregnant' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'status' : MotherhoodStatus,
  'country' : IDL.Opt(Country),
  'favorites' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'location' : IDL.Opt(Region),
});
export const Reply = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'author' : IDL.Text,
  'timestamp' : Time,
  'postId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countryIsFrance' : IDL.Func([], [IDL.Bool], ['query']),
  'countryIsSwitzerland' : IDL.Func([], [IDL.Bool], ['query']),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ProductCondition,
        Region,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'createPost' : IDL.Func([Category, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'createReply' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'getAllConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerCountry' : IDL.Func([], [IDL.Opt(Country)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Conversation)],
      ['query'],
    ),
  'getFavoritedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [Listing], ['query']),
  'getListingCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getListingsByCondition' : IDL.Func(
      [ProductCondition],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getListingsByRegion' : IDL.Func([Region], [IDL.Vec(Listing)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
  'getRepliesByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Reply)], ['query']),
  'getUserActivity' : IDL.Func(
      [IDL.Principal],
      [IDL.Record({ 'listings' : IDL.Vec(Listing), 'posts' : IDL.Vec(Post) })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductCondition = IDL.Variant({
    'new' : IDL.Null,
    'veryGood' : IDL.Null,
    'good' : IDL.Null,
    'used' : IDL.Null,
  });
  const Region = IDL.Variant({
    'fribourg' : IDL.Null,
    'jura' : IDL.Null,
    'vaud' : IDL.Null,
    'valais' : IDL.Null,
    'geneva' : IDL.Null,
    'neuchatel' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'postpartum' : IDL.Null,
    'sleep' : IDL.Null,
    'mentalLoad' : IDL.Null,
    'organization' : IDL.Null,
    'pregnancy' : IDL.Null,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'participant1' : IDL.Principal,
    'participant2' : IDL.Principal,
    'messages' : IDL.Vec(Message),
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'region' : Region,
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
    'price' : IDL.Nat,
    'ageGroup' : IDL.Text,
    'condition' : ProductCondition,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'author' : IDL.Text,
    'timestamp' : Time,
    'category' : Category,
  });
  const Country = IDL.Variant({
    'france' : IDL.Null,
    'switzerland' : IDL.Null,
  });
  const MotherhoodStatus = IDL.Variant({
    'adultChildren' : IDL.Null,
    'postpartum' : IDL.Null,
    'tryingToConceive' : IDL.Null,
    'youngChildren' : IDL.Null,
    'teenChildren' : IDL.Null,
    'pregnant' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'status' : MotherhoodStatus,
    'country' : IDL.Opt(Country),
    'favorites' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'location' : IDL.Opt(Region),
  });
  const Reply = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'author' : IDL.Text,
    'timestamp' : Time,
    'postId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countryIsFrance' : IDL.Func([], [IDL.Bool], ['query']),
    'countryIsSwitzerland' : IDL.Func([], [IDL.Bool], ['query']),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ProductCondition,
          Region,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func([Category, IDL.Text, IDL.Bool], [IDL.Nat], []),
    'createReply' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [IDL.Nat], []),
    'getAllConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerCountry' : IDL.Func([], [IDL.Opt(Country)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'getFavoritedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [Listing], ['query']),
    'getListingCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getListingsByCondition' : IDL.Func(
        [ProductCondition],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getListingsByRegion' : IDL.Func([Region], [IDL.Vec(Listing)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
    'getRepliesByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Reply)], ['query']),
    'getUserActivity' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'listings' : IDL.Vec(Listing),
            'posts' : IDL.Vec(Post),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };