/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Conversation {
    id: bigint;
    participant1: Principal;
    participant2: Principal;
    messages: Array<Message>;
}
export interface Reply {
    id: bigint;
    content: string;
    isAnonymous: boolean;
    author: string;
    isHidden: boolean;
    timestamp: Time;
    postId: bigint;
}
export type Time = bigint;
export interface Listing {
    id: bigint;
    region: Region;
    categories: Array<string>;
    title: string;
    favorites: Array<Principal>;
    description: string;
    author: string;
    timestamp: Time;
    price: bigint;
    ageGroup: string;
    condition: ProductCondition;
    images: Array<ExternalBlob>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface AdminModerationItem {
    id: bigint;
    contentId: bigint;
    reportCount: bigint;
    contentType: string;
    author: string;
    timestamp: Time;
    excerpt: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Region = {
    __kind__: "swissCanton";
    swissCanton: SwissCanton;
} | {
    __kind__: "frenchRegion";
    frenchRegion: FrenchRegion;
};
export interface AdminReportedContent {
    id: bigint;
    contentId: bigint;
    content: string;
    reportCount: bigint;
    contentType: AdminReportType;
    author: string;
    isHidden: boolean;
    timestamp: Time;
}
export interface AdminStats {
    franceUsers: bigint;
    totalForumPosts: bigint;
    activeListings: bigint;
    reportedContentCount: bigint;
    totalUsers: bigint;
    switzerlandUsers: bigint;
    totalComments: bigint;
    newUsersLast7Days: bigint;
}
export interface Post {
    id: bigint;
    content: string;
    isAnonymous: boolean;
    author: string;
    isHidden: boolean;
    timestamp: Time;
    category: Category;
}
export interface AdminActivityEntry {
    id: bigint;
    activityType: AdminActivityType;
    content: string;
    author: string;
    timestamp: Time;
}
export interface Message {
    id: bigint;
    content: string;
    sender: Principal;
    timestamp: Time;
    receiver: Principal;
}
export interface UserProfile {
    bio?: string;
    region?: Region;
    status: MotherhoodStatus;
    country?: Country;
    favorites: Array<bigint>;
    marketingOptIn: boolean;
    listings: Array<bigint>;
    name: string;
    email?: string;
    rulesAccepted: boolean;
    posts: Array<bigint>;
    profilePicture?: ExternalBlob;
    registrationTime: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AdminActivityType {
    secondHandListing = "secondHandListing",
    forumPost = "forumPost",
    comment = "comment",
    userRegistration = "userRegistration"
}
export enum AdminReportType {
    post = "post",
    comment = "comment"
}
export enum Category {
    postpartum = "postpartum",
    sleep = "sleep",
    mentalLoad = "mentalLoad",
    organization = "organization",
    pregnancy = "pregnancy"
}
export enum Country {
    france = "france",
    switzerland = "switzerland"
}
export enum FrenchRegion {
    bourgogneFrancheComte = "bourgogneFrancheComte",
    corse = "corse",
    auvergneRhoneAlpes = "auvergneRhoneAlpes",
    centreValDeLoire = "centreValDeLoire",
    paysDeLaLoire = "paysDeLaLoire",
    hautsDeFrance = "hautsDeFrance",
    normandie = "normandie",
    ileDeFrance = "ileDeFrance",
    occitanie = "occitanie",
    nouvelleAquitaine = "nouvelleAquitaine",
    provenceAlpesCoteAzur = "provenceAlpesCoteAzur",
    bretagne = "bretagne",
    grandEst = "grandEst"
}
export enum MotherhoodStatus {
    adultChildren = "adultChildren",
    postpartum = "postpartum",
    tryingToConceive = "tryingToConceive",
    youngChildren = "youngChildren",
    teenChildren = "teenChildren",
    pregnant = "pregnant"
}
export enum ProductCondition {
    new_ = "new",
    veryGood = "veryGood",
    good = "good",
    used = "used"
}
export enum SwissCanton {
    fribourg = "fribourg",
    jura = "jura",
    vaud = "vaud",
    valais = "valais",
    geneva = "geneva",
    neuchatel = "neuchatel"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminGetAllContentForModeration(): Promise<Array<AdminModerationItem>>;
    adminGetRecentActivity(): Promise<Array<AdminActivityEntry>>;
    adminGetReportedContent(): Promise<Array<AdminReportedContent>>;
    adminGetStats(): Promise<AdminStats>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createListing(title: string, description: string, price: bigint, condition: ProductCondition, region: Region, categories: Array<string>, ageGroup: string, images: Array<ExternalBlob>): Promise<bigint>;
    createPost(category: Category, content: string, isAnonymous: boolean): Promise<bigint>;
    createReply(postId: bigint, content: string, isAnonymous: boolean): Promise<bigint>;
    getAllConversations(): Promise<Array<Conversation>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(participant: Principal): Promise<Conversation | null>;
    getCurrentPrincipalId(): Promise<string>;
    getFavoritedListings(): Promise<Array<Listing>>;
    getPublicAllListings(): Promise<Array<Listing>>;
    getPublicAllPosts(): Promise<Array<Post>>;
    getPublicListing(listingId: bigint): Promise<Listing>;
    getPublicListingsByCondition(condition: ProductCondition): Promise<Array<Listing>>;
    getPublicListingsByRegion(region: Region): Promise<Array<Listing>>;
    getPublicPost(postId: bigint): Promise<Post>;
    getPublicPostsByCategory(category: Category): Promise<Array<Post>>;
    getRepliesByPost(postId: bigint): Promise<Array<Reply>>;
    getUserActivity(user: Principal): Promise<{
        listings: Array<Listing>;
        posts: Array<Post>;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isFavorite(listingId: bigint): Promise<boolean>;
    reportContent(contentType: AdminReportType, contentId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(receiver: Principal, content: string): Promise<bigint>;
    toggleFavorite(listingId: bigint): Promise<boolean>;
}
import type { AdminActivityEntry as _AdminActivityEntry, AdminActivityType as _AdminActivityType, AdminReportType as _AdminReportType, AdminReportedContent as _AdminReportedContent, Category as _Category, Conversation as _Conversation, Country as _Country, ExternalBlob as _ExternalBlob, FrenchRegion as _FrenchRegion, Listing as _Listing, MotherhoodStatus as _MotherhoodStatus, Post as _Post, ProductCondition as _ProductCondition, Region as _Region, SwissCanton as _SwissCanton, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminGetAllContentForModeration(): Promise<Array<AdminModerationItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllContentForModeration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllContentForModeration();
            return result;
        }
    }
    async adminGetRecentActivity(): Promise<Array<AdminActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetRecentActivity();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetRecentActivity();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetReportedContent(): Promise<Array<AdminReportedContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetReportedContent();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetReportedContent();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetStats();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createListing(arg0: string, arg1: string, arg2: bigint, arg3: ProductCondition, arg4: Region, arg5: Array<string>, arg6: string, arg7: Array<ExternalBlob>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2, to_candid_ProductCondition_n20(this._uploadFile, this._downloadFile, arg3), to_candid_Region_n22(this._uploadFile, this._downloadFile, arg4), arg5, arg6, await to_candid_vec_n28(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2, to_candid_ProductCondition_n20(this._uploadFile, this._downloadFile, arg3), to_candid_Region_n22(this._uploadFile, this._downloadFile, arg4), arg5, arg6, await to_candid_vec_n28(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async createPost(arg0: Category, arg1: string, arg2: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_Category_n30(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_Category_n30(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async createReply(arg0: bigint, arg1: string, arg2: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReply(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReply(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConversations();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<Conversation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentPrincipalId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentPrincipalId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentPrincipalId();
            return result;
        }
    }
    async getFavoritedListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavoritedListings();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavoritedListings();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicAllListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicAllListings();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicAllListings();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicAllPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicAllPosts();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicAllPosts();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicListing(arg0: bigint): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicListing(arg0);
                return from_candid_Listing_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicListing(arg0);
            return from_candid_Listing_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicListingsByCondition(arg0: ProductCondition): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicListingsByCondition(to_candid_ProductCondition_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicListingsByCondition(to_candid_ProductCondition_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicListingsByRegion(arg0: Region): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicListingsByRegion(to_candid_Region_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicListingsByRegion(to_candid_Region_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicPost(arg0: bigint): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicPost(arg0);
                return from_candid_Post_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicPost(arg0);
            return from_candid_Post_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicPostsByCategory(arg0: Category): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicPostsByCategory(to_candid_Category_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicPostsByCategory(to_candid_Category_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepliesByPost(arg0: bigint): Promise<Array<Reply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepliesByPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepliesByPost(arg0);
            return result;
        }
    }
    async getUserActivity(arg0: Principal): Promise<{
        listings: Array<Listing>;
        posts: Array<Post>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserActivity(arg0);
                return from_candid_record_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserActivity(arg0);
            return from_candid_record_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFavorite(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFavorite(arg0);
            return result;
        }
    }
    async reportContent(arg0: AdminReportType, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportContent(to_candid_AdminReportType_n65(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportContent(to_candid_AdminReportType_n65(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n67(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n67(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async toggleFavorite(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFavorite(arg0);
            return result;
        }
    }
}
function from_candid_AdminActivityEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminActivityEntry): AdminActivityEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_AdminActivityType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminActivityType): AdminActivityType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_AdminReportType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminReportType): AdminReportType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_AdminReportedContent_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminReportedContent): AdminReportedContent {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Country_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Country): Country {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FrenchRegion_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FrenchRegion): FrenchRegion {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_Listing_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Promise<Listing> {
    return await from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_MotherhoodStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MotherhoodStatus): MotherhoodStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCondition_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCondition): ProductCondition {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Region_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Region): Region {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_SwissCanton_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SwissCanton): SwissCanton {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Region]): Region | null {
    return value.length === 0 ? null : from_candid_Region_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Country]): Country | null {
    return value.length === 0 ? null : from_candid_Country_n46(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Conversation]): Conversation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    activityType: _AdminActivityType;
    content: string;
    author: string;
    timestamp: _Time;
}): {
    id: bigint;
    activityType: AdminActivityType;
    content: string;
    author: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        activityType: from_candid_AdminActivityType_n11(_uploadFile, _downloadFile, value.activityType),
        content: value.content,
        author: value.author,
        timestamp: value.timestamp
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contentId: bigint;
    content: string;
    reportCount: bigint;
    contentType: _AdminReportType;
    author: string;
    isHidden: boolean;
    timestamp: _Time;
}): {
    id: bigint;
    contentId: bigint;
    content: string;
    reportCount: bigint;
    contentType: AdminReportType;
    author: string;
    isHidden: boolean;
    timestamp: Time;
} {
    return {
        id: value.id,
        contentId: value.contentId,
        content: value.content,
        reportCount: value.reportCount,
        contentType: from_candid_AdminReportType_n16(_uploadFile, _downloadFile, value.contentType),
        author: value.author,
        isHidden: value.isHidden,
        timestamp: value.timestamp
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    region: [] | [_Region];
    status: _MotherhoodStatus;
    country: [] | [_Country];
    favorites: Array<bigint>;
    marketingOptIn: boolean;
    listings: Array<bigint>;
    name: string;
    email: [] | [string];
    rulesAccepted: boolean;
    posts: Array<bigint>;
    profilePicture: [] | [_ExternalBlob];
    registrationTime: _Time;
}): Promise<{
    bio?: string;
    region?: Region;
    status: MotherhoodStatus;
    country?: Country;
    favorites: Array<bigint>;
    marketingOptIn: boolean;
    listings: Array<bigint>;
    name: string;
    email?: string;
    rulesAccepted: boolean;
    posts: Array<bigint>;
    profilePicture?: ExternalBlob;
    registrationTime: Time;
}> {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.bio)),
        region: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.region)),
        status: from_candid_MotherhoodStatus_n43(_uploadFile, _downloadFile, value.status),
        country: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.country)),
        favorites: value.favorites,
        marketingOptIn: value.marketingOptIn,
        listings: value.listings,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.email)),
        rulesAccepted: value.rulesAccepted,
        posts: value.posts,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n48(_uploadFile, _downloadFile, value.profilePicture)),
        registrationTime: value.registrationTime
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: _Region;
    categories: Array<string>;
    title: string;
    favorites: Array<Principal>;
    description: string;
    author: string;
    timestamp: _Time;
    price: bigint;
    ageGroup: string;
    condition: _ProductCondition;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    region: Region;
    categories: Array<string>;
    title: string;
    favorites: Array<Principal>;
    description: string;
    author: string;
    timestamp: Time;
    price: bigint;
    ageGroup: string;
    condition: ProductCondition;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        region: from_candid_Region_n37(_uploadFile, _downloadFile, value.region),
        categories: value.categories,
        title: value.title,
        favorites: value.favorites,
        description: value.description,
        author: value.author,
        timestamp: value.timestamp,
        price: value.price,
        ageGroup: value.ageGroup,
        condition: from_candid_ProductCondition_n56(_uploadFile, _downloadFile, value.condition),
        images: await from_candid_vec_n58(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    isAnonymous: boolean;
    author: string;
    isHidden: boolean;
    timestamp: _Time;
    category: _Category;
}): {
    id: bigint;
    content: string;
    isAnonymous: boolean;
    author: string;
    isHidden: boolean;
    timestamp: Time;
    category: Category;
} {
    return {
        id: value.id,
        content: value.content,
        isAnonymous: value.isAnonymous,
        author: value.author,
        isHidden: value.isHidden,
        timestamp: value.timestamp,
        category: from_candid_Category_n62(_uploadFile, _downloadFile, value.category)
    };
}
async function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    listings: Array<_Listing>;
    posts: Array<_Post>;
}): Promise<{
    listings: Array<Listing>;
    posts: Array<Post>;
}> {
    return {
        listings: await from_candid_vec_n53(_uploadFile, _downloadFile, value.listings),
        posts: from_candid_vec_n59(_uploadFile, _downloadFile, value.posts)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    secondHandListing: null;
} | {
    forumPost: null;
} | {
    comment: null;
} | {
    userRegistration: null;
}): AdminActivityType {
    return "secondHandListing" in value ? AdminActivityType.secondHandListing : "forumPost" in value ? AdminActivityType.forumPost : "comment" in value ? AdminActivityType.comment : "userRegistration" in value ? AdminActivityType.userRegistration : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    post: null;
} | {
    comment: null;
}): AdminReportType {
    return "post" in value ? AdminReportType.post : "comment" in value ? AdminReportType.comment : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    swissCanton: _SwissCanton;
} | {
    frenchRegion: _FrenchRegion;
}): {
    __kind__: "swissCanton";
    swissCanton: SwissCanton;
} | {
    __kind__: "frenchRegion";
    frenchRegion: FrenchRegion;
} {
    return "swissCanton" in value ? {
        __kind__: "swissCanton",
        swissCanton: from_candid_SwissCanton_n39(_uploadFile, _downloadFile, value.swissCanton)
    } : "frenchRegion" in value ? {
        __kind__: "frenchRegion",
        frenchRegion: from_candid_FrenchRegion_n41(_uploadFile, _downloadFile, value.frenchRegion)
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fribourg: null;
} | {
    jura: null;
} | {
    vaud: null;
} | {
    valais: null;
} | {
    geneva: null;
} | {
    neuchatel: null;
}): SwissCanton {
    return "fribourg" in value ? SwissCanton.fribourg : "jura" in value ? SwissCanton.jura : "vaud" in value ? SwissCanton.vaud : "valais" in value ? SwissCanton.valais : "geneva" in value ? SwissCanton.geneva : "neuchatel" in value ? SwissCanton.neuchatel : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bourgogneFrancheComte: null;
} | {
    corse: null;
} | {
    auvergneRhoneAlpes: null;
} | {
    centreValDeLoire: null;
} | {
    paysDeLaLoire: null;
} | {
    hautsDeFrance: null;
} | {
    normandie: null;
} | {
    ileDeFrance: null;
} | {
    occitanie: null;
} | {
    nouvelleAquitaine: null;
} | {
    provenceAlpesCoteAzur: null;
} | {
    bretagne: null;
} | {
    grandEst: null;
}): FrenchRegion {
    return "bourgogneFrancheComte" in value ? FrenchRegion.bourgogneFrancheComte : "corse" in value ? FrenchRegion.corse : "auvergneRhoneAlpes" in value ? FrenchRegion.auvergneRhoneAlpes : "centreValDeLoire" in value ? FrenchRegion.centreValDeLoire : "paysDeLaLoire" in value ? FrenchRegion.paysDeLaLoire : "hautsDeFrance" in value ? FrenchRegion.hautsDeFrance : "normandie" in value ? FrenchRegion.normandie : "ileDeFrance" in value ? FrenchRegion.ileDeFrance : "occitanie" in value ? FrenchRegion.occitanie : "nouvelleAquitaine" in value ? FrenchRegion.nouvelleAquitaine : "provenceAlpesCoteAzur" in value ? FrenchRegion.provenceAlpesCoteAzur : "bretagne" in value ? FrenchRegion.bretagne : "grandEst" in value ? FrenchRegion.grandEst : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adultChildren: null;
} | {
    postpartum: null;
} | {
    tryingToConceive: null;
} | {
    youngChildren: null;
} | {
    teenChildren: null;
} | {
    pregnant: null;
}): MotherhoodStatus {
    return "adultChildren" in value ? MotherhoodStatus.adultChildren : "postpartum" in value ? MotherhoodStatus.postpartum : "tryingToConceive" in value ? MotherhoodStatus.tryingToConceive : "youngChildren" in value ? MotherhoodStatus.youngChildren : "teenChildren" in value ? MotherhoodStatus.teenChildren : "pregnant" in value ? MotherhoodStatus.pregnant : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    france: null;
} | {
    switzerland: null;
}): Country {
    return "france" in value ? Country.france : "switzerland" in value ? Country.switzerland : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    veryGood: null;
} | {
    good: null;
} | {
    used: null;
}): ProductCondition {
    return "new" in value ? ProductCondition.new : "veryGood" in value ? ProductCondition.veryGood : "good" in value ? ProductCondition.good : "used" in value ? ProductCondition.used : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    postpartum: null;
} | {
    sleep: null;
} | {
    mentalLoad: null;
} | {
    organization: null;
} | {
    pregnancy: null;
}): Category {
    return "postpartum" in value ? Category.postpartum : "sleep" in value ? Category.sleep : "mentalLoad" in value ? Category.mentalLoad : "organization" in value ? Category.organization : "pregnancy" in value ? Category.pregnancy : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminReportedContent>): Array<AdminReportedContent> {
    return value.map((x)=>from_candid_AdminReportedContent_n14(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Promise<Array<Listing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Listing_n54(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n49(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n60(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminActivityEntry>): Array<AdminActivityEntry> {
    return value.map((x)=>from_candid_AdminActivityEntry_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AdminReportType_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminReportType): _AdminReportType {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_Country_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Country): _Country {
    return to_candid_variant_n72(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FrenchRegion_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FrenchRegion): _FrenchRegion {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_MotherhoodStatus_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotherhoodStatus): _MotherhoodStatus {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCondition_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCondition): _ProductCondition {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Region_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): _Region {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_SwissCanton_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SwissCanton): _SwissCanton {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    region?: Region;
    status: MotherhoodStatus;
    country?: Country;
    favorites: Array<bigint>;
    marketingOptIn: boolean;
    listings: Array<bigint>;
    name: string;
    email?: string;
    rulesAccepted: boolean;
    posts: Array<bigint>;
    profilePicture?: ExternalBlob;
    registrationTime: Time;
}): Promise<{
    bio: [] | [string];
    region: [] | [_Region];
    status: _MotherhoodStatus;
    country: [] | [_Country];
    favorites: Array<bigint>;
    marketingOptIn: boolean;
    listings: Array<bigint>;
    name: string;
    email: [] | [string];
    rulesAccepted: boolean;
    posts: Array<bigint>;
    profilePicture: [] | [_ExternalBlob];
    registrationTime: _Time;
}> {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        region: value.region ? candid_some(to_candid_Region_n22(_uploadFile, _downloadFile, value.region)) : candid_none(),
        status: to_candid_MotherhoodStatus_n69(_uploadFile, _downloadFile, value.status),
        country: value.country ? candid_some(to_candid_Country_n71(_uploadFile, _downloadFile, value.country)) : candid_none(),
        favorites: value.favorites,
        marketingOptIn: value.marketingOptIn,
        listings: value.listings,
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        rulesAccepted: value.rulesAccepted,
        posts: value.posts,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.profilePicture)) : candid_none(),
        registrationTime: value.registrationTime
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCondition): {
    new: null;
} | {
    veryGood: null;
} | {
    good: null;
} | {
    used: null;
} {
    return value == ProductCondition.new ? {
        new_: null
    } : value == ProductCondition.veryGood ? {
        veryGood: null
    } : value == ProductCondition.good ? {
        good: null
    } : value == ProductCondition.used ? {
        used: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "swissCanton";
    swissCanton: SwissCanton;
} | {
    __kind__: "frenchRegion";
    frenchRegion: FrenchRegion;
}): {
    swissCanton: _SwissCanton;
} | {
    frenchRegion: _FrenchRegion;
} {
    return value.__kind__ === "swissCanton" ? {
        swissCanton: to_candid_SwissCanton_n26(_uploadFile, _downloadFile, value.swissCanton)
    } : value.__kind__ === "frenchRegion" ? {
        frenchRegion: to_candid_FrenchRegion_n24(_uploadFile, _downloadFile, value.frenchRegion)
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FrenchRegion): {
    bourgogneFrancheComte: null;
} | {
    corse: null;
} | {
    auvergneRhoneAlpes: null;
} | {
    centreValDeLoire: null;
} | {
    paysDeLaLoire: null;
} | {
    hautsDeFrance: null;
} | {
    normandie: null;
} | {
    ileDeFrance: null;
} | {
    occitanie: null;
} | {
    nouvelleAquitaine: null;
} | {
    provenceAlpesCoteAzur: null;
} | {
    bretagne: null;
} | {
    grandEst: null;
} {
    return value == FrenchRegion.bourgogneFrancheComte ? {
        bourgogneFrancheComte: null
    } : value == FrenchRegion.corse ? {
        corse: null
    } : value == FrenchRegion.auvergneRhoneAlpes ? {
        auvergneRhoneAlpes: null
    } : value == FrenchRegion.centreValDeLoire ? {
        centreValDeLoire: null
    } : value == FrenchRegion.paysDeLaLoire ? {
        paysDeLaLoire: null
    } : value == FrenchRegion.hautsDeFrance ? {
        hautsDeFrance: null
    } : value == FrenchRegion.normandie ? {
        normandie: null
    } : value == FrenchRegion.ileDeFrance ? {
        ileDeFrance: null
    } : value == FrenchRegion.occitanie ? {
        occitanie: null
    } : value == FrenchRegion.nouvelleAquitaine ? {
        nouvelleAquitaine: null
    } : value == FrenchRegion.provenceAlpesCoteAzur ? {
        provenceAlpesCoteAzur: null
    } : value == FrenchRegion.bretagne ? {
        bretagne: null
    } : value == FrenchRegion.grandEst ? {
        grandEst: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SwissCanton): {
    fribourg: null;
} | {
    jura: null;
} | {
    vaud: null;
} | {
    valais: null;
} | {
    geneva: null;
} | {
    neuchatel: null;
} {
    return value == SwissCanton.fribourg ? {
        fribourg: null
    } : value == SwissCanton.jura ? {
        jura: null
    } : value == SwissCanton.vaud ? {
        vaud: null
    } : value == SwissCanton.valais ? {
        valais: null
    } : value == SwissCanton.geneva ? {
        geneva: null
    } : value == SwissCanton.neuchatel ? {
        neuchatel: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    postpartum: null;
} | {
    sleep: null;
} | {
    mentalLoad: null;
} | {
    organization: null;
} | {
    pregnancy: null;
} {
    return value == Category.postpartum ? {
        postpartum: null
    } : value == Category.sleep ? {
        sleep: null
    } : value == Category.mentalLoad ? {
        mentalLoad: null
    } : value == Category.organization ? {
        organization: null
    } : value == Category.pregnancy ? {
        pregnancy: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminReportType): {
    post: null;
} | {
    comment: null;
} {
    return value == AdminReportType.post ? {
        post: null
    } : value == AdminReportType.comment ? {
        comment: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotherhoodStatus): {
    adultChildren: null;
} | {
    postpartum: null;
} | {
    tryingToConceive: null;
} | {
    youngChildren: null;
} | {
    teenChildren: null;
} | {
    pregnant: null;
} {
    return value == MotherhoodStatus.adultChildren ? {
        adultChildren: null
    } : value == MotherhoodStatus.postpartum ? {
        postpartum: null
    } : value == MotherhoodStatus.tryingToConceive ? {
        tryingToConceive: null
    } : value == MotherhoodStatus.youngChildren ? {
        youngChildren: null
    } : value == MotherhoodStatus.teenChildren ? {
        teenChildren: null
    } : value == MotherhoodStatus.pregnant ? {
        pregnant: null
    } : value;
}
function to_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Country): {
    france: null;
} | {
    switzerland: null;
} {
    return value == Country.france ? {
        france: null
    } : value == Country.switzerland ? {
        switzerland: null
    } : value;
}
async function to_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n29(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
