/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Reply {
    id: bigint;
    content: string;
    isAnonymous: boolean;
    author: string;
    timestamp: Time;
    postId: bigint;
}
export type Time = bigint;
export interface Listing {
    id: bigint;
    region: Region;
    categories: Array<string>;
    title: string;
    description: string;
    author: string;
    timestamp: Time;
    price: bigint;
    ageGroup: string;
    condition: ProductCondition;
    images: Array<ExternalBlob>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Post {
    id: bigint;
    content: string;
    isAnonymous: boolean;
    author: string;
    timestamp: Time;
    category: Category;
}
export interface Message {
    id: bigint;
    content: string;
    sender: Principal;
    timestamp: Time;
    receiver: Principal;
}
export interface Conversation {
    id: bigint;
    participant1: Principal;
    participant2: Principal;
    messages: Array<Message>;
}
export interface UserProfile {
    bio?: string;
    status: MotherhoodStatus;
    favorites: Array<bigint>;
    name: string;
    profilePicture?: ExternalBlob;
    location?: Region;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    postpartum = "postpartum",
    sleep = "sleep",
    mentalLoad = "mentalLoad",
    organization = "organization",
    pregnancy = "pregnancy"
}
export enum MotherhoodStatus {
    adultChildren = "adultChildren",
    postpartum = "postpartum",
    tryingToConceive = "tryingToConceive",
    youngChildren = "youngChildren",
    teenChildren = "teenChildren",
    pregnant = "pregnant"
}
export enum ProductCondition {
    new_ = "new",
    veryGood = "veryGood",
    good = "good",
    used = "used"
}
export enum Region {
    fribourg = "fribourg",
    jura = "jura",
    vaud = "vaud",
    valais = "valais",
    geneva = "geneva",
    neuchatel = "neuchatel"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createListing(title: string, description: string, price: bigint, condition: ProductCondition, region: Region, categories: Array<string>, ageGroup: string, images: Array<ExternalBlob>): Promise<bigint>;
    createPost(category: Category, content: string, isAnonymous: boolean): Promise<bigint>;
    createReply(postId: bigint, content: string, isAnonymous: boolean): Promise<bigint>;
    getAllConversations(): Promise<Array<Conversation>>;
    getAllListings(): Promise<Array<Listing>>;
    getAllPosts(): Promise<Array<Post>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(participant: Principal): Promise<Conversation | null>;
    getFavoritedListings(): Promise<Array<Listing>>;
    getListing(listingId: bigint): Promise<Listing>;
    getListingCount(): Promise<bigint>;
    getListingsByCondition(condition: ProductCondition): Promise<Array<Listing>>;
    getListingsByRegion(region: Region): Promise<Array<Listing>>;
    getPost(postId: bigint): Promise<Post>;
    getPostsByCategory(category: Category): Promise<Array<Post>>;
    getRepliesByPost(postId: bigint): Promise<Array<Reply>>;
    getUserActivity(user: Principal): Promise<{
        listings: Array<Listing>;
        posts: Array<Post>;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isFavorite(listingId: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(receiver: Principal, content: string): Promise<bigint>;
    toggleFavorite(listingId: bigint): Promise<boolean>;
}
import type { Category as _Category, Conversation as _Conversation, ExternalBlob as _ExternalBlob, Listing as _Listing, MotherhoodStatus as _MotherhoodStatus, Post as _Post, ProductCondition as _ProductCondition, Region as _Region, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createListing(arg0: string, arg1: string, arg2: bigint, arg3: ProductCondition, arg4: Region, arg5: Array<string>, arg6: string, arg7: Array<ExternalBlob>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2, to_candid_ProductCondition_n10(this.uploadFile, this.downloadFile, arg3), to_candid_Region_n12(this.uploadFile, this.downloadFile, arg4), arg5, arg6, await to_candid_vec_n14(this.uploadFile, this.downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2, to_candid_ProductCondition_n10(this.uploadFile, this.downloadFile, arg3), to_candid_Region_n12(this.uploadFile, this.downloadFile, arg4), arg5, arg6, await to_candid_vec_n14(this.uploadFile, this.downloadFile, arg7));
            return result;
        }
    }
    async createPost(arg0: Category, arg1: string, arg2: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_Category_n16(this.uploadFile, this.downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_Category_n16(this.uploadFile, this.downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async createReply(arg0: bigint, arg1: string, arg2: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReply(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReply(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConversations();
            return result;
        }
    }
    async getAllListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this.uploadFile, this.downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<Conversation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_opt_n42(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_opt_n42(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFavoritedListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavoritedListings();
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavoritedListings();
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getListing(arg0: bigint): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_Listing_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_Listing_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getListingCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingCount();
            return result;
        }
    }
    async getListingsByCondition(arg0: ProductCondition): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsByCondition(to_candid_ProductCondition_n10(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsByCondition(to_candid_ProductCondition_n10(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getListingsByRegion(arg0: Region): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsByRegion(to_candid_Region_n12(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsByRegion(to_candid_Region_n12(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPost(arg0: bigint): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_Post_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_Post_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPostsByCategory(arg0: Category): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByCategory(to_candid_Category_n16(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByCategory(to_candid_Category_n16(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRepliesByPost(arg0: bigint): Promise<Array<Reply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepliesByPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepliesByPost(arg0);
            return result;
        }
    }
    async getUserActivity(arg0: Principal): Promise<{
        listings: Array<Listing>;
        posts: Array<Post>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserActivity(arg0);
                return from_candid_record_n43(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserActivity(arg0);
            return from_candid_record_n43(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFavorite(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFavorite(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n44(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n44(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async toggleFavorite(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFavorite(arg0);
            return result;
        }
    }
}
function from_candid_Category_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n31(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_Listing_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Promise<Listing> {
    return await from_candid_record_n20(uploadFile, downloadFile, value);
}
function from_candid_MotherhoodStatus_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MotherhoodStatus): MotherhoodStatus {
    return from_candid_variant_n37(uploadFile, downloadFile, value);
}
function from_candid_Post_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n29(uploadFile, downloadFile, value);
}
function from_candid_ProductCondition_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCondition): ProductCondition {
    return from_candid_variant_n24(uploadFile, downloadFile, value);
}
function from_candid_Region_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Region): Region {
    return from_candid_variant_n22(uploadFile, downloadFile, value);
}
async function from_candid_UserProfile_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n34(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
async function from_candid_opt_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n33(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n26(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Region]): Region | null {
    return value.length === 0 ? null : from_candid_Region_n21(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Conversation]): Conversation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: _Region;
    categories: Array<string>;
    title: string;
    description: string;
    author: string;
    timestamp: _Time;
    price: bigint;
    ageGroup: string;
    condition: _ProductCondition;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    region: Region;
    categories: Array<string>;
    title: string;
    description: string;
    author: string;
    timestamp: Time;
    price: bigint;
    ageGroup: string;
    condition: ProductCondition;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        region: from_candid_Region_n21(uploadFile, downloadFile, value.region),
        categories: value.categories,
        title: value.title,
        description: value.description,
        author: value.author,
        timestamp: value.timestamp,
        price: value.price,
        ageGroup: value.ageGroup,
        condition: from_candid_ProductCondition_n23(uploadFile, downloadFile, value.condition),
        images: await from_candid_vec_n25(uploadFile, downloadFile, value.images)
    };
}
function from_candid_record_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    isAnonymous: boolean;
    author: string;
    timestamp: _Time;
    category: _Category;
}): {
    id: bigint;
    content: string;
    isAnonymous: boolean;
    author: string;
    timestamp: Time;
    category: Category;
} {
    return {
        id: value.id,
        content: value.content,
        isAnonymous: value.isAnonymous,
        author: value.author,
        timestamp: value.timestamp,
        category: from_candid_Category_n30(uploadFile, downloadFile, value.category)
    };
}
async function from_candid_record_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    status: _MotherhoodStatus;
    favorites: Array<bigint>;
    name: string;
    profilePicture: [] | [_ExternalBlob];
    location: [] | [_Region];
}): Promise<{
    bio?: string;
    status: MotherhoodStatus;
    favorites: Array<bigint>;
    name: string;
    profilePicture?: ExternalBlob;
    location?: Region;
}> {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n35(uploadFile, downloadFile, value.bio)),
        status: from_candid_MotherhoodStatus_n36(uploadFile, downloadFile, value.status),
        favorites: value.favorites,
        name: value.name,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n38(uploadFile, downloadFile, value.profilePicture)),
        location: record_opt_to_undefined(from_candid_opt_n39(uploadFile, downloadFile, value.location))
    };
}
async function from_candid_record_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    listings: Array<_Listing>;
    posts: Array<_Post>;
}): Promise<{
    listings: Array<Listing>;
    posts: Array<Post>;
}> {
    return {
        listings: await from_candid_vec_n18(uploadFile, downloadFile, value.listings),
        posts: from_candid_vec_n27(uploadFile, downloadFile, value.posts)
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fribourg: null;
} | {
    jura: null;
} | {
    vaud: null;
} | {
    valais: null;
} | {
    geneva: null;
} | {
    neuchatel: null;
}): Region {
    return "fribourg" in value ? Region.fribourg : "jura" in value ? Region.jura : "vaud" in value ? Region.vaud : "valais" in value ? Region.valais : "geneva" in value ? Region.geneva : "neuchatel" in value ? Region.neuchatel : value;
}
function from_candid_variant_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    veryGood: null;
} | {
    good: null;
} | {
    used: null;
}): ProductCondition {
    return "new" in value ? ProductCondition.new : "veryGood" in value ? ProductCondition.veryGood : "good" in value ? ProductCondition.good : "used" in value ? ProductCondition.used : value;
}
function from_candid_variant_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    postpartum: null;
} | {
    sleep: null;
} | {
    mentalLoad: null;
} | {
    organization: null;
} | {
    pregnancy: null;
}): Category {
    return "postpartum" in value ? Category.postpartum : "sleep" in value ? Category.sleep : "mentalLoad" in value ? Category.mentalLoad : "organization" in value ? Category.organization : "pregnancy" in value ? Category.pregnancy : value;
}
function from_candid_variant_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adultChildren: null;
} | {
    postpartum: null;
} | {
    tryingToConceive: null;
} | {
    youngChildren: null;
} | {
    teenChildren: null;
} | {
    pregnant: null;
}): MotherhoodStatus {
    return "adultChildren" in value ? MotherhoodStatus.adultChildren : "postpartum" in value ? MotherhoodStatus.postpartum : "tryingToConceive" in value ? MotherhoodStatus.tryingToConceive : "youngChildren" in value ? MotherhoodStatus.youngChildren : "teenChildren" in value ? MotherhoodStatus.teenChildren : "pregnant" in value ? MotherhoodStatus.pregnant : value;
}
function from_candid_variant_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Promise<Array<Listing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Listing_n19(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n26(uploadFile, downloadFile, x)));
}
function from_candid_vec_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n28(uploadFile, downloadFile, x));
}
function to_candid_Category_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n17(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_MotherhoodStatus_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotherhoodStatus): _MotherhoodStatus {
    return to_candid_variant_n47(uploadFile, downloadFile, value);
}
function to_candid_ProductCondition_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCondition): _ProductCondition {
    return to_candid_variant_n11(uploadFile, downloadFile, value);
}
function to_candid_Region_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): _Region {
    return to_candid_variant_n13(uploadFile, downloadFile, value);
}
async function to_candid_UserProfile_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n45(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    status: MotherhoodStatus;
    favorites: Array<bigint>;
    name: string;
    profilePicture?: ExternalBlob;
    location?: Region;
}): Promise<{
    bio: [] | [string];
    status: _MotherhoodStatus;
    favorites: Array<bigint>;
    name: string;
    profilePicture: [] | [_ExternalBlob];
    location: [] | [_Region];
}> {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        status: to_candid_MotherhoodStatus_n46(uploadFile, downloadFile, value.status),
        favorites: value.favorites,
        name: value.name,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n15(uploadFile, downloadFile, value.profilePicture)) : candid_none(),
        location: value.location ? candid_some(to_candid_Region_n12(uploadFile, downloadFile, value.location)) : candid_none()
    };
}
function to_candid_variant_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCondition): {
    new: null;
} | {
    veryGood: null;
} | {
    good: null;
} | {
    used: null;
} {
    return value == ProductCondition.new ? {
        new_: null
    } : value == ProductCondition.veryGood ? {
        veryGood: null
    } : value == ProductCondition.good ? {
        good: null
    } : value == ProductCondition.used ? {
        used: null
    } : value;
}
function to_candid_variant_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): {
    fribourg: null;
} | {
    jura: null;
} | {
    vaud: null;
} | {
    valais: null;
} | {
    geneva: null;
} | {
    neuchatel: null;
} {
    return value == Region.fribourg ? {
        fribourg: null
    } : value == Region.jura ? {
        jura: null
    } : value == Region.vaud ? {
        vaud: null
    } : value == Region.valais ? {
        valais: null
    } : value == Region.geneva ? {
        geneva: null
    } : value == Region.neuchatel ? {
        neuchatel: null
    } : value;
}
function to_candid_variant_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    postpartum: null;
} | {
    sleep: null;
} | {
    mentalLoad: null;
} | {
    organization: null;
} | {
    pregnancy: null;
} {
    return value == Category.postpartum ? {
        postpartum: null
    } : value == Category.sleep ? {
        sleep: null
    } : value == Category.mentalLoad ? {
        mentalLoad: null
    } : value == Category.organization ? {
        organization: null
    } : value == Category.pregnancy ? {
        pregnancy: null
    } : value;
}
function to_candid_variant_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotherhoodStatus): {
    adultChildren: null;
} | {
    postpartum: null;
} | {
    tryingToConceive: null;
} | {
    youngChildren: null;
} | {
    teenChildren: null;
} | {
    pregnant: null;
} {
    return value == MotherhoodStatus.adultChildren ? {
        adultChildren: null
    } : value == MotherhoodStatus.postpartum ? {
        postpartum: null
    } : value == MotherhoodStatus.tryingToConceive ? {
        tryingToConceive: null
    } : value == MotherhoodStatus.youngChildren ? {
        youngChildren: null
    } : value == MotherhoodStatus.teenChildren ? {
        teenChildren: null
    } : value == MotherhoodStatus.pregnant ? {
        pregnant: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n15(uploadFile, downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
